import '../constants/enums.dart';

/// Represents a log message generated by the [DownloadManager].
///
/// Contains the actual [message] and its associated severity [level],
/// which can be used for filtering or displaying logs appropriately.
class LogRecord {
  /// The log message content.
  final String message;

  /// The severity level of the log message (e.g., debug, info, warning, error).
  final LogLevel level;

  /// Creates a new [LogRecord] with the given [message] and [level].
  LogRecord({required this.message, required this.level});
}
